# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "$DB_PASSWORD"

  sk_backend:
    image: sixkube
    restart: always
    ports:
      - 3000:3000
    environment:
      POSTGRES_PASSWORD: "$DB_PASSWORD"
