default: &default
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: sqlite3

produciton:
  adapter: postgresql
  encoding: unicode
  host: sixkube-postgres
  username: postgres
  password: $POSTGRES_PASSWORD
  pool: 5

test:
  <<: *default
  database: db/test.sqlite3
