default: &default
  adapter: postgresql
  encoding: unicode
  host: sixkube-postgres
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: postgres

test:
  <<: *default
  database: postgres
