default: &default
  adapter: postgresql
  encoding: unicode
  host: sixkube-postgres
  username: postgres
  password: $POSTGRES_PASSWORD
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  host: sixkube.com
  username: postgres
  password: $POSTGRES_PASSWORD
  pool: 5
  database: postgres

test:
  <<: *default
  database: postgres
