default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: $POSTGRES_PASSWORD
  pool: 5

development:
  <<: *default
  database: sixkube-postgres

test:
  <<: *default
  database: sixkube-postgres
